Seabeta 540 new action plan
UKGovernmentBEIS/beis-simple-energy-advice-beta pull request #109
Opened 2022-06-24 15:14 UTC by CodrinCotarlanSoftwire

2022-06-24 15:24 UTC, CodrinCotarlanSoftwire commented on SeaPublicWebsite/Views/EnergyEfficiency/ActionPlan/Partials/ReturnToActionPlanPartial.cshtml
> +@{ await Html.RenderPartialAsync("SendEmailPartial.cshtml", new YourSavedRecommendationsEmailViewModel()); }
Allows me to very nicely use only a small view model for the email button, instead of the entire model from this file.

2022-06-27 10:31 UTC, DanCorderSoftwire requested changes

2022-06-27 10:58 UTC, CodrinCotarlanSoftwire commented on SeaPublicWebsite/Views/Shared/_Recommendation.cshtml
> +                            // TODO: Change this
This was the easiest way I could think of to do it at the time. I created a ticket to change this into a better alternative (and added the number in the comment)

2022-06-27 11:28 UTC, DanCorderSoftwire approved these changes

2022-06-27 12:45 UTC, merged