PC-572-Loft Insulation Recommendation fix
UKGovernmentBEIS/beis-simple-energy-advice-beta pull request #259
Opened 2024-01-26 11:03 UTC by CalPinSW

https://beisdigital.atlassian.net/browse/PC-572
- Update YearBuilt enum to include all dates from EPC API
- Update Tests 
- Update GetBreConstructionDate switch statement

2024-01-30 12:29 UTC, davidm-m approved these changes
Looks sensible to me!

2024-01-30 19:52 UTC, jamiehumphries commented
⚠️ I think we need to more carefully consider what happens with existing data.

At the moment, any old enum values in the database will be erroneously mapped to the new values.

2024-01-30 19:52 UTC, jamiehumphries requested changes
I'm concerned about what will happen with old data. I don't think this is ready yet.

2024-01-30 19:52 UTC, jamiehumphries commented on SeaPublicWebsite.BusinessLogic/ExternalServices/Bre/RecommendationService.cs
> +
Please can you make sure not to commit these whitespace errors.

2024-02-01 13:03 UTC, jamiehumphries commented
Superceded by https://github.com/UKGovernmentBEIS/beis-simple-energy-advice-beta/pull/261.

2024-02-01 13:03 UTC, jamiehumphries commented
Superceded by https://github.com/UKGovernmentBEIS/beis-simple-energy-advice-beta/pull/261.

2024-02-01 13:03 UTC, closed without merging