PC-1508: Review & Synchronise Linter Rules
UKGovernmentBEIS/beis-simple-energy-advice-beta pull request #317
Opened 2024-12-23 12:09 UTC by samyou-softwire

[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1508)

# Description

adds a 'DESNZ' formatting profile. this is identical to Built-in: Full cleanup, minus the 'Add/remove braces for single statement' rule.

we have opted out of shared settings on our projects, as we .gitignore `SimpleEnergyAdvice.sln.DotSettings`, the default repo shared settings layer. for this exception, this PR adds a new settings layer containing our shared cleanup rules. if we would rather not an extra layer, can look into using the default shared settings. see https://www.jetbrains.com/help/rider/2024.3/Sharing_Configuration_Options.html for more info

# Checklist

- [x] I have made any necessary updates to the documentation
- [x] I have checked there are no unnecessary IDE warnings in this PR
- [x] I have checked there are no unintentional line ending changes
- [x] I have added tests where applicable
 
# Screenshots

![image](https://github.com/user-attachments/assets/dbb19e73-9695-4db6-9cdb-821f1ea3e9bc)

2024-12-30 12:20 UTC, jdgage requested changes
I think remove `SimpleEnergyAdvice.sln.DotSettings` from the gitignore, rather than have a new file. That's what I'd expect to see (and is effectively what we're doing). It was probably added because there was no agreed standard before.

On the 'Add/remove braces for single statement' - why leave that one out? Does that mean it will or won't require braces for single statements?

2024-12-31 09:30 UTC, samyou-softwire commented
> I think remove `SimpleEnergyAdvice.sln.DotSettings` from the gitignore, rather than have a new file. That's what I'd expect to see (and is effectively what we're doing). It was probably added because there was no agreed standard before.

I've moved it to the shared team settings file

> On the 'Add/remove braces for single statement' - why leave that one out? Does that mean it will or won't require braces for single statements?

looks like theres no rule that forces braces for all statements (including single line ones), so best we can do for now is disable the rule that optimises single lines to remove braces

2024-12-31 11:30 UTC, jdgage approved these changes

2024-12-31 11:32 UTC, samyou-softwire commented
will hold off on merging this for now until the 2nd jan release

2025-01-02 10:09 UTC, merged