Seabeta 312 feedback survey
UKGovernmentBEIS/beis-simple-energy-advice-beta pull request #37
Opened 2022-05-31 15:45 UTC by CodrinCotarlanSoftwire

2022-05-31 15:46 UTC, CodrinCotarlanSoftwire commented on SeaPublicWebsite/Controllers/FeedbackController.cs
> -[Route("feedback")]
Decided to use the same controller for both feedback forms

2022-05-31 15:48 UTC, CodrinCotarlanSoftwire commented on SeaPublicWebsite/Views/Shared/_Layout.cshtml
> -        @if (ViewBag.ServiceUnavailable != true)
This wasn't set _anywhere_

2022-05-31 15:48 UTC, CodrinCotarlanSoftwire commented on SeaPublicWebsite/Views/Shared/_Layout.cshtml
> +                       if (ViewBag.OnFeedbackPage is true)
ViewBag :(
Works quite well in this case, though

2022-05-31 16:35 UTC, DanCorderSoftwire requested changes

2022-05-31 16:35 UTC, DanCorderSoftwire commented on SeaPublicWebsite/Controllers/FeedbackController.cs
> +        ViewBag.OnFeedbackPage = true;
Should we have this on the `FeedbackForm_Get` method too?

2022-05-31 16:35 UTC, DanCorderSoftwire commented on SeaPublicWebsite/Controllers/FeedbackController.cs
> +            ModelState.AddModelError(nameof(viewModel.VisitReasonList), "Please select at least one option");
I don't think these error messages match the Gov UK style (see https://design-system.service.gov.uk/components/checkboxes/)
e.g. this one should be something like "Select at least one reason that you came to the site today"

2022-05-31 16:35 UTC, DanCorderSoftwire commented on SeaPublicWebsite/Controllers/FeedbackController.cs
> +            ViewBag.OnFeedbackPage = true;
This should be `return FeedbackSurvey_Get()`?
Then you won't need to set the ViewBag either.

2022-05-31 16:35 UTC, DanCorderSoftwire commented on SeaPublicWebsite/Controllers/FeedbackController.cs
> +            ViewBag.OnFeedbackPage = true;
Can you fix `FeedbackForm_Post` at the same time please?

2022-05-31 16:35 UTC, DanCorderSoftwire commented on SeaPublicWebsite/Views/Feedback/FeedbackSurvey.cshtml
> +            <fieldset class="govuk-fieldset">
I'm not sure using a `fieldset` and `legend` here makes sense?
Can you just use the `h1` and `p` on their own?

2022-06-01 10:33 UTC, DanCorderSoftwire approved these changes

2022-06-01 10:34 UTC, merged